Object protection_electricity_effect
name protection_electricity
face protection_electricity_effect.111
anim
protection_electricity_effect.111
protection_electricity_effect.112
protection_electricity_effect.113
protection_electricity_effect.114
protection_electricity_effect.115
protection_electricity_effect.116
mina
speed 0.5
food 6
is_used_up 1
no_pick 1
map_layer fly
end
