char *def_sounds[] = {
"#\n",
"# This is a reasonably heavily modified version of the sounds file from\n",
"# the server.\n",
"#\n",
"# Since the client has to load the sounds on its own, full path names\n",
"# are needed.\n",
"#\n",
"# There are two sections - one for normal sounds, and one for spell\n",
"# sounds.  They are differentiated by the header 'Standard Sounds:' and\n",
"# 'Spell Sounds:'\n",
"#\n",
"# Empty lines and lines starting with # are ignored.\n",
"#\n",
"# Format of the file:  pathname to sound, default volume (what volume gets\n",
"# played if it is centered on the player), symbolic name (not currently\n",
"# used for anything, but may be in the future for the server to communicated\n",
"# to the client), and sound number..  Symbolic name and sound number may\n",
"# be ommitted.  If sound number is missing, the sound will be assigned one\n",
"# higher than the last sound read in.\n",
"#\n",
"# the symbolic name can be DEFAULT, in which case all sounds for that section\n",
"# which are otherwise not set will be set to that value.  This can be\n",
"# especially useful for that magic section, since new spells get added\n",
"# fairly often.\n",
"#\n",
"# The volume of 100 means max volume.  Anything higher may break the sound\n",
"# handling.\n",
"#\n",
"# The server currently communicates what sound to play via the sound\n",
"# number - you should not change those.  However, you can change most\n",
"# of the other sounds without problem.\n",
"#\n",
"# If a copy of this file is in ~/.wograld/, it will be loaded\n",
"#\n",
"Standard Sounds:\n",
"\n",
"/su-fanf.raw	 30	SOUND_NEW_PLAYER	0\n",
"/Teeswing.raw 	 80	SOUND_FIRE_ARROW	1\n",
"/chord.raw	100	SOUND_LEARN_SPELL	2\n",
"/Missed.raw	 70	SOUND_FUMBLE_SPELL	3\n",
"/Missed.raw	 70	SOUND_WAND_POOF		4\n",
"/Creaky-1.raw	 90	SOUND_OPEN_DOOR		5\n",
"/blip.raw 	 80	SOUND_PUSH_PLAYER	6\n",
"/click1.raw	 60	SOUND_PLAYER_HITS1	7\n",
"/click2.raw	 70	SOUND_PLAYER_HITS2	8\n",
"/click1.raw	 80	SOUND_PLAYER_HITS3	9\n",
"/click2.raw	 90	SOUND_PLAYER_HITS4	10\n",
"/FloorTom.raw	 70	SOUND_PLAYER_IS_HIT1	11\n",
"/ouch1.raw	 80	SOUND_PLAYER_IS_HIT2	12\n",
"/thru.raw 	 90	SOUND_PLAYER_IS_HIT3	13\n",
"/drip.raw 	 80	SOUND_PLAYER_KILLS	14\n",
"/squish.raw	 80	SOUND_PET_IS_KILLED	15\n",
"/gong.raw 	150	SOUND_PLAYER_DIES	16\n",
"/Whoosh.raw	100	SOUND_OB_EVAPORATE	17\n",
"/Explosion.raw	100	SOUND_OB_EXPLODE	18\n",
"/TowerClock.raw	130	SOUND_CLOCK		19\n",
"/boink2.raw 	 80	SOUND_TURN_HANDLE	20\n",
"/MetalCrash.raw 	200	SOUND_FALL_HOLE		21\n",
"/Puke.raw 	130	SOUND_DRINK_POISON     	22\n",
"\n",
"# Spells :		SOUND_CAST_SPELL_0      23, 24, 25 ...\n",
"Spell Sounds:\n",
"\n",
"/magic.raw	100	DEFAULT\n",
"/swish.raw	 70	\"magic bullet\" 			/* 0 */\n",
"/swish.raw	 60	\"small fireball\"\n",
"/swish.raw	 80	\"medium fireball\"\n",
"/swish.raw	100	\"large fireball\"\n",
"/magic.raw	100	\"burning hands\"\n",
"/lightning1.raw	 70	\"small lightning\"\n",
"/lightning1.raw	 90	\"large lightning\"\n",
"/swish.raw	100	\"magic missile\"\n",
"/magic.raw	100	\"create bomb\"\n",
"/magic.raw	100	\"summon golem\"\n",
"/magic.raw	100	\"summon fire elemental\"		/* 10 */\n",
"/magic.raw	100	\"summon earth elemental\"\n",
"/magic.raw	100	\"summon water elemental\"\n",
"/magic.raw	100	\"summon air elemental\"\n",
"/first_try.raw	100	\"dimension door\"\n",
"/magic.raw	100	\"create earth wall\"\n",
"/Tear.raw 	100	\"paralyze\"\n",
"/Missle1.raw	 80	\"icestorm\"\n",
"/magic.raw	100	\"magic mapping\"\n",
"/Tear.raw 	 90	\"turn undead\"\n",
"/Tear.raw 	 90	\"fear\"				/* 20 */\n",
"/Missle1.raw	100	\"poison cloud\"\n",
"/magic.raw	100	\"wonder\"\n",
"/Explosion.raw	 80	\"destruction\"\n",
"/magic.raw	100	\"perceive self\"\n",
"/sci_fi_gun.raw	100	\"word of recall\"\n",
"/magic.raw	100	\"invisible\"\n",
"/magic.raw	100	\"invisible to undead\"\n",
"/magic.raw	100	\"probe\"\n",
"/swish.raw	100	\"large bullet\"\n",
"/magic.raw	100	\"improved invisibility\"		/* 30 */\n",
"/Tear.raw 	100	\"holy word\"\n",
"/magic.raw	100	\"minor healing\"\n",
"/magic.raw	100	\"medium healing\"\n",
"/magic.raw	100	\"major healing\"\n",
"/magic.raw	100	\"heal\"\n",
"/magic.raw	100	\"create food\"\n",
"/Explosion.raw	 60	\"earth to dust\"\n",
"/magic.raw	100	\"armour\"\n",
"/magic.raw	100	\"strength\"\n",
"/magic.raw	100	\"dexterity\"			/* 40 */\n",
"/magic.raw	100	\"constitution\"\n",
"/magic.raw	100	\"charisma\"\n",
"/magic.raw	100	\"create fire wall\"\n",
"/magic.raw	100	\"create frost wall\"\n",
"/magic.raw	100	\"protection from cold\"\n",
"/magic.raw	100	\"protection from electricity\"\n",
"/magic.raw	100	\"protection from fire\"\n",
"/magic.raw	100	\"protection from poison\"\n",
"/magic.raw	100	\"protection from slow\"\n",
"/magic.raw	100	\"protection from paralysis\"	/* 50 */\n",
"/magic.raw	100	\"protection from draining\"\n",
"/magic.raw	100	\"protection from magic\"\n",
"/magic.raw	100	\"protection from attack\"\n",
"/magic.raw	100	\"levitate\"\n",
"/Gun-5.raw	100	\"small speedball\"\n",
"/Gun-5.raw	130	\"large speedball\"\n",
"/Missle1.raw	150	\"hellfire\"\n",
"/Missle1.raw	170	\"dragonbreath\"\n",
"/Missle1.raw	170	\"large icestorm\"\n",
"/magic.raw	100	\"charging\"			/* 60 */\n",
"/magic.raw	100	\"polymorph\"\n",
"/swish.raw	200	\"cancellation\"\n",
"/Tear.raw 	100	\"confusion\"\n",
"/Tear.raw 	150	\"mass confusion\"\n",
"/magic.raw	100	\"summon pet monster\"\n",
"/magic.raw 	100	\"slow\"\n",
"/magic.raw	100	\"regenerate spellpoints\"\n",
"/magic.raw	100	\"cure poison\"\n",
"/magic.raw	100	\"protection from confusion\"\n",
"/magic.raw	100	\"protection from cancellation\"	/* 70 */\n",
"/magic.raw	100	\"protection from depletion\"\n",
"/magic.raw	100	\"alchemy\"\n",
"/Evil_Laugh.raw	100	\"remove curse\"\n",
"/Evil_Laugh.raw	120	\"remove damnation\"\n",
"/magic.raw	100	\"identify\"\n",
"/magic.raw	100	\"detect magic\"\n",
"/magic.raw	100	\"detect monster\"\n",
"/magic.raw	100	\"detect evil\"\n",
"/magic.raw	100	\"detect curse\"\n",
"/Explosion.raw	100	\"heroism\"			/* 80 */\n",
"/bugle_charge.raw	100	\"aggravation\"\n",
"/magic.raw	100	\"firebolt\"\n",
"/magic.raw	100	\"frostbolt\"\n",
"/Explosion.raw	100	\"shockwave\"\n",
"/magic.raw	100	\"color spray\"\n",
"/magic.raw	100	\"haste\"\n",
"/magic.raw	100	\"face of death\"\n",
"/lightning1.raw	110	\"ball lightning\"\n",
"/swish.raw	100	\"meteor swarm\"\n",
"/swish.raw	100	\"comet\"				/* 90 */\n",
"/magic.raw	100	\"mystic fist\"\n",
"/magic.raw	100	\"raise dead\"\n",
"/magic.raw	100	\"resurrection\"\n",
"/magic.raw	100	\"reincarnation\"\n",
"/magic.raw	100	\"immune cold\"\n",
"/magic.raw	100	\"immune electricity\"\n",
"/magic.raw	100	\"immune fire\"\n",
"/magic.raw	100	\"immune poison\"\n",
"/magic.raw	100	\"immune slow\"\n",
"/magic.raw	100	\"immune paralysis\"		/* 100 */\n",
"/magic.raw	100	\"immune drain\"\n",
"/magic.raw	100	\"immune magic\"\n",
"/magic.raw	100	\"immune attack\"\n",
"/magic.raw	100	\"invulnerability\"\n",
"/magic.raw	100	\"defense\n",
"/magic.raw	100	\"rune fire\"\n",
"/magic.raw	100	\"rune frost\"\n",
"/magic.raw	100	\"rune shocking\"\n",
"/magic.raw	100	\"rune blasting\"\n",
"/magic.raw	100	\"rune death\"			/* 110 */\n",
"/magic.raw	100	\"marking rune\"\n",
"/magic.raw	100	\"build director\"\n",
"/magic.raw	100	\"pool of chaos\"\n",
"/magic.raw	100	\"build bullet wall\"\n",
"/magic.raw	100	\"build ligtning wall\"\n",
"/magic.raw	100	\"build fireball wall\"\n",
"/magic.raw	100	\"magic \"\n",
"/magic.raw	100	\"rune of magic drain\"\n",
"/magic.raw	100	\"antimagic rune\"\n",
"/magic.raw	100	\"rune transferrence\"		/* 120 */\n",
"/magic.raw	100	\"transferrence\"\n",
"/magic.raw	100	\"magic drain\"\n",
"/magic.raw	100	\"counterspell\"\n",
"/magic.raw	100	\"disarm\"\n",
"/magic.raw	100	\"cure confusion\"\n",
"/magic.raw	100	\"restoration\"\n",
"/magic.raw	100	\"summon evil monster\"\n",
"/magic.raw	100	\"counterwall\"\n",
"/magic.raw	100	\"cause light wounds\"\n",
"/magic.raw	100	\"cause medium wounds\"		/* 130 */\n",
"/magic.raw	100	\"cause serious wounds\"\n",
"/magic.raw	100	\"charm monsters\"\n",
"/magic.raw	100	\"banishment\"\n",
"/magic.raw	100	\"create missile\"\n",
};
