
#line 3 "reader.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer rmap_create_buffer
#define yy_delete_buffer rmap_delete_buffer
#define yy_flex_debug rmap_flex_debug
#define yy_init_buffer rmap_init_buffer
#define yy_flush_buffer rmap_flush_buffer
#define yy_load_buffer_state rmap_load_buffer_state
#define yy_switch_to_buffer rmap_switch_to_buffer
#define yyin rmapin
#define yyleng rmapleng
#define yylex rmaplex
#define yylineno rmaplineno
#define yyout rmapout
#define yyrestart rmaprestart
#define yytext rmaptext
#define yywrap rmapwrap
#define yyalloc rmapalloc
#define yyrealloc rmaprealloc
#define yyfree rmapfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE rmaprestart(rmapin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t rmapleng;

extern FILE *rmapin, *rmapout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up rmaptext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up rmaptext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via rmaprestart()), so that the user can continue scanning by
	 * just pointing rmapin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when rmaptext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t rmapleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow rmapwrap()'s to do buffer switches
 * instead of setting up a fresh rmapin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void rmaprestart (FILE *input_file  );
void rmap_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE rmap_create_buffer (FILE *file,int size  );
void rmap_delete_buffer (YY_BUFFER_STATE b  );
void rmap_flush_buffer (YY_BUFFER_STATE b  );
void rmappush_buffer_state (YY_BUFFER_STATE new_buffer  );
void rmappop_buffer_state (void );

static void rmapensure_buffer_stack (void );
static void rmap_load_buffer_state (void );
static void rmap_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER rmap_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE rmap_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE rmap_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE rmap_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *rmapalloc (yy_size_t  );
void *rmaprealloc (void *,yy_size_t  );
void rmapfree (void *  );

#define yy_new_buffer rmap_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        rmapensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            rmap_create_buffer(rmapin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        rmapensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            rmap_create_buffer(rmapin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define rmapwrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *rmapin = (FILE *) 0, *rmapout = (FILE *) 0;

typedef int yy_state_type;

extern int rmaplineno;

int rmaplineno = 1;

extern char *rmaptext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr rmaptext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up rmaptext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	rmapleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 34
#define YY_END_OF_BUFFER 35
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[339] =
    {   0,
       33,   33,    0,    0,   35,   33,   31,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   34,   34,   33,   33,   32,   33,   31,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,    0,   31,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,

       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,    8,    8,    9,    9,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   29,   29,   33,

       33,   33,   33,   33,   33,   33,   33,   33,   10,   10,
       33,   33,   33,   33,   33,   33,   33,   24,   24,   25,
       25,   33,   14,   14,   33,   33,   33,   33,   33,   33,
       33,    6,    6,   33,   33,   33,   18,   18,   33,   22,
       22,   33,   33,   33,   33,   33,   33,   33,   33,   33,
        1,    1,   33,    7,    7,   15,   15,   33,   33,   33,
       33,   33,    2,    2,   33,   33,   33,   33,   26,   26,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
        5,    5,   33,   23,   23,   27,   27,   33,   33,   17,
       17,   33,   33,   33,   20,   20,   33,   33,   33,   33,

        3,    3,   33,   33,   33,   21,   21,   19,   19,   33,
       33,   33,   33,   33,    4,    4,   33,   33,   11,   11,
       12,   12,   13,   13,   33,   33,   33,   28,   28,   33,
       33,   33,   30,   30,   33,   16,   16,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    5,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    6,    7,
        8,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    9,    1,   10,   11,   12,   13,
       14,   15,   16,    1,    1,   17,   18,   19,   20,   21,
        1,   22,   23,   24,   25,   26,   27,   28,   29,   30,
        1,    1,    1,   31,   32,    1,   33,    1,   34,   35,

       36,   37,   38,   39,   40,    1,    1,   41,   42,   43,
       44,   45,    1,   46,   47,   48,   49,   50,   51,   52,
       53,   54,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[55] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[373] =
    {   0,
        0,   31,   83,   84,  619,    0,  620,  615,    0,   77,
       77,   64,   78,   87,   78,   77,   91,   72,   81,   95,
       82,   83,  620,    4,    0,  614,  620,    5,    0,   96,
       98,   96,   90,   92,  120,  118,  118,  110,  121,  126,
      124,  126,  133,  129,  131,  132,    6,  620,  131,  130,
      138,  130,  139,  130,  146,  147,  137,  138,  136,  172,
      174,  169,  179,  172,  160,  161,  167,  171,  178,  172,
      184,  174,  179,  182,  178,  176,  178,  184,  188,  185,
      195,  207,  209,  221,  222,  212,  216,  227,  214,  220,
      217,  222,  232,  584,  221,  221,  234,  223,  229,  231,

      226,  226,  228,  613,  612,  237,  234,  254,  255,  252,
      263,  254,  265,  606,  267,  262,  267,  266,  280,  580,
      579,  269,  270,  264,  608,  607,  284,  271,  267,  280,
      281,  576,  282,  575,  272,  292,  274,  305,  304,  306,
      306,  313,  309,  304,  322,  318,    0,  604,    0,  603,
      602,  320,  320,  314,  327,  329,  331,  331,  601,  324,
      330,  325,  322,  350,  360,  368,  600,  599,  366,  598,
      359,  368,  597,  361,  371,  355,  596,  373,  374,  378,
      595,  372,  594,  593,  377,  374,  374,  363,  373,  373,
      592,  591,  383,  590,  375,  373,  589,    0,  588,  380,

      587,  420,  586,  403,  399,  408,  585,  408,    0,  584,
      583,  582,  409,  418,  414,  413,  581,    0,  580,    0,
      579,  422,    0,  578,  410,  406,  577,  413,  576,  575,
      421,    0,  574,  414,  427,  428,    0,  573,  432,    0,
      572,  571,  423,  570,  431,  569,  568,  567,  428,  428,
        0,  566,  565,    0,  564,    0,  563,  427,  432,  455,
      562,  456,    0,  561,  451,  560,  559,  558,    0,  557,
      556,  455,  464,  555,  467,  554,  553,  552,  521,    6,
        0,  550,  549,    0,  548,    0,  547,  459,  546,    0,
      545,  457,  544,  543,    0,  542,  462,  541,  540,  539,

        0,  538,  458,  537,  470,    0,  536,    0,  535,  474,
      534,  533,  532,  531,    0,  530,  475,  464,    0,  529,
        0,  528,    0,  527,  526,  463,  525,    0,  524,  475,
      523,  522,    0,  521,  520,    0,  519,  620,  511,  513,
      519,  515,  518,  517,  494,  493,  492,  491,  490,  489,
      488,  487,  427,   90,   89,   29,   28,   27,   26,   25,
       24,   23,   22,   21,   20,   19,   18,   17,   16,   15,
       14,    0
    } ;

static yyconst flex_int16_t yy_def[373] =
    {   0,
      339,  338,  340,  340,  338,  341,  338,  342,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  338,  338,  341,  342,  338,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  338,  338,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,

      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  343,  344,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  343,  343,  344,  344,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  345,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  346,  341,  341,  341,  341,  341,  341,  341,
      347,  348,  341,  349,  341,  341,  341,  345,  345,  341,

      341,  341,  350,  341,  341,  341,  351,  341,  346,  346,
      352,  341,  341,  341,  341,  341,  341,  347,  347,  348,
      348,  341,  349,  349,  341,  341,  353,  341,  354,  355,
      341,  350,  350,  341,  341,  341,  351,  351,  341,  352,
      352,  356,  341,  341,  341,  341,  357,  341,  341,  341,
      353,  353,  341,  354,  354,  355,  355,  341,  341,  341,
      341,  341,  356,  356,  341,  358,  341,  359,  357,  357,
      360,  341,  341,  361,  341,  341,  341,  362,  341,  341,
      358,  358,  363,  359,  359,  360,  360,  341,  341,  361,
      361,  341,  364,  365,  362,  362,  341,  341,  341,  341,

      363,  363,  341,  366,  341,  364,  364,  365,  365,  341,
      367,  368,  369,  341,  366,  366,  341,  341,  367,  367,
      368,  368,  369,  369,  370,  341,  341,  370,  370,  341,
      371,  341,  371,  371,  372,  372,  372,    0,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338
    } ;

static yyconst flex_uint16_t yy_nxt[675] =
    {   0,
      336,   28,    7,    8,   29,   47,   28,   47,   48,   29,
       48,  298,  299,  300,  333,  328,  323,  321,  319,  315,
      308,  306,  301,  295,  290,  286,  284,  281,  269,  263,
        9,    6,    6,    7,    8,    6,    6,    6,    6,   10,
        6,   11,   12,   13,    6,    6,    6,   14,   15,    6,
       16,    6,   17,   18,   19,    6,    6,   20,   21,   22,
        6,    9,    6,   10,    6,   11,   12,   13,    6,    6,
        6,   14,   15,    6,   16,    6,   17,   18,   19,    6,
        6,   20,   21,   22,    6,    7,    7,   30,   31,  256,
      254,   35,   32,   36,   37,   38,   33,   39,   40,   41,

       42,   34,   43,   44,   45,   46,   49,   50,   51,   52,
       53,   30,   31,   24,   24,   35,   32,   36,   37,   38,
       33,   39,   40,   41,   42,   34,   43,   44,   45,   46,
       49,   50,   51,   52,   53,   54,   56,   57,   58,   59,
       55,   60,   61,   62,   63,   64,   65,   66,   67,   68,
       69,   70,   71,   72,   73,   74,   75,   76,   77,   54,
       56,   57,   58,   59,   55,   60,   61,   62,   63,   64,
       65,   66,   67,   68,   69,   70,   71,   72,   73,   74,
       75,   76,   77,   78,   80,   79,   81,   82,   83,   84,
       85,   86,   87,   88,   89,   90,   91,   93,   94,   95,

       96,   97,   98,   99,  100,   92,  101,   78,   80,   79,
       81,   82,   83,   84,   85,   86,   87,   88,   89,   90,
       91,   93,   94,   95,   96,   97,   98,   99,  100,  102,
      101,  103,  104,  105,  106,  107,  109,  110,  108,  111,
      112,  113,  114,  116,  117,  118,  119,  120,  121,  122,
      123,  124,  127,  102,  128,  103,  104,  105,  106,  107,
      109,  110,  108,  111,  112,  113,  114,  116,  117,  118,
      119,  120,  121,  122,  123,  124,  127,  129,  128,  130,
      131,  132,  133,  134,  136,  137,  138,  140,  141,  139,
      144,  145,  146,  151,  152,  153,  154,  155,  157,  159,

      160,  129,  161,  130,  131,  132,  133,  134,  136,  137,
      138,  140,  141,  139,  144,  145,  146,  151,  152,  153,
      154,  155,  157,  159,  160,  162,  161,  163,  164,  165,
      166,  169,  170,  171,  172,  174,  175,  176,  177,  178,
      167,  168,  181,  182,  184,  179,  185,  180,  186,  162,
      187,  163,  164,  165,  166,  169,  170,  171,  172,  174,
      175,  176,  177,  178,  167,  168,  181,  182,  184,  179,
      185,  180,  186,  188,  187,  189,  190,  193,  195,  197,
      200,  196,  201,  202,  204,  205,  206,  208,  212,  213,
      214,  215,  216,  217,  222,  225,  226,  188,  228,  189,

      190,  193,  195,  197,  200,  196,  201,  202,  204,  205,
      206,  208,  212,  213,  214,  215,  216,  217,  222,  225,
      226,  230,  228,  234,  235,  236,  239,  251,  243,  244,
      245,  246,  248,  249,  250,  253,  258,  259,  260,  261,
      262,  265,  267,  272,  273,  275,  276,  234,  235,  236,
      239,  231,  243,  244,  245,  246,  248,  249,  250,  253,
      258,  259,  260,  261,  262,  265,  267,  272,  273,  275,
      276,  277,  279,  280,  288,  289,  292,  303,  305,  310,
      314,  317,  318,  326,  327,  330,  332,  240,  237,  232,
      223,  220,  218,  209,  198,  277,  279,  280,  288,  289,

      292,  303,  305,  310,  314,  317,  318,  326,  327,  330,
      332,    6,    6,   23,   23,   26,   26,  149,  147,   25,
      337,  337,  334,  335,  334,  329,  331,  329,  324,  322,
      320,  316,  325,  324,  322,  320,  309,  307,  316,  302,
      313,  312,  311,  296,  309,  307,  291,  304,  287,  285,
      302,  282,  297,  296,  294,  293,  291,  287,  270,  285,
      283,  282,  264,  278,  257,  255,  274,  252,  271,  270,
      268,  266,  264,  241,  238,  233,  257,  255,  252,  224,
      221,  219,  247,  242,  241,  210,  238,  233,  229,  199,
      227,  224,  221,  219,  211,  210,  207,  203,  199,  194,

      192,  191,  183,  173,  150,  148,  158,  156,  150,  148,
      143,  142,  135,  126,  125,  115,   27,   27,  338,    5,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338
    } ;

static yyconst flex_int16_t yy_chk[675] =
    {   0,
      372,    9,    1,    1,    9,   24,   28,   47,   24,   28,
       47,  280,  280,  280,  371,  370,  369,  368,  367,  366,
      365,  364,  363,  362,  361,  360,  359,  358,  357,  356,
        1,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    3,    4,   10,   11,  355,
      354,   12,   11,   13,   13,   14,   11,   15,   16,   17,

       18,   11,   19,   20,   21,   22,   30,   31,   32,   33,
       34,   10,   11,    3,    4,   12,   11,   13,   13,   14,
       11,   15,   16,   17,   18,   11,   19,   20,   21,   22,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       35,   40,   41,   42,   43,   44,   45,   46,   49,   50,
       51,   52,   53,   54,   55,   56,   57,   58,   59,   35,
       36,   37,   38,   39,   35,   40,   41,   42,   43,   44,
       45,   46,   49,   50,   51,   52,   53,   54,   55,   56,
       57,   58,   59,   60,   61,   60,   62,   63,   64,   65,
       66,   67,   68,   69,   70,   71,   72,   73,   74,   75,

       76,   77,   78,   79,   80,   72,   81,   60,   61,   60,
       62,   63,   64,   65,   66,   67,   68,   69,   70,   71,
       72,   73,   74,   75,   76,   77,   78,   79,   80,   82,
       81,   83,   84,   85,   86,   87,   88,   89,   87,   90,
       91,   92,   93,   95,   96,   97,   98,   99,  100,  101,
      102,  103,  106,   82,  107,   83,   84,   85,   86,   87,
       88,   89,   87,   90,   91,   92,   93,   95,   96,   97,
       98,   99,  100,  101,  102,  103,  106,  108,  107,  109,
      110,  111,  112,  113,  115,  116,  117,  118,  119,  117,
      122,  123,  124,  127,  128,  129,  130,  131,  133,  135,

      136,  108,  137,  109,  110,  111,  112,  113,  115,  116,
      117,  118,  119,  117,  122,  123,  124,  127,  128,  129,
      130,  131,  133,  135,  136,  138,  137,  139,  140,  141,
      142,  143,  144,  145,  146,  152,  153,  154,  155,  156,
      142,  142,  157,  158,  160,  156,  161,  156,  162,  138,
      163,  139,  140,  141,  142,  143,  144,  145,  146,  152,
      153,  154,  155,  156,  142,  142,  157,  158,  160,  156,
      161,  156,  162,  164,  163,  165,  166,  169,  171,  172,
      174,  171,  175,  176,  178,  179,  180,  182,  185,  186,
      187,  188,  189,  190,  193,  195,  196,  164,  200,  165,

      166,  169,  171,  172,  174,  171,  175,  176,  178,  179,
      180,  182,  185,  186,  187,  188,  189,  190,  193,  195,
      196,  202,  200,  204,  205,  206,  208,  353,  213,  214,
      215,  216,  222,  225,  226,  228,  231,  234,  235,  236,
      239,  243,  245,  249,  250,  258,  259,  204,  205,  206,
      208,  202,  213,  214,  215,  216,  222,  225,  226,  228,
      231,  234,  235,  236,  239,  243,  245,  249,  250,  258,
      259,  260,  262,  265,  272,  273,  275,  288,  292,  297,
      303,  305,  310,  317,  318,  326,  330,  352,  351,  350,
      349,  348,  347,  346,  345,  260,  262,  265,  272,  273,

      275,  288,  292,  297,  303,  305,  310,  317,  318,  326,
      330,  339,  339,  340,  340,  342,  342,  344,  343,  341,
      337,  335,  334,  332,  331,  329,  327,  325,  324,  322,
      320,  316,  314,  313,  312,  311,  309,  307,  304,  302,
      300,  299,  298,  296,  294,  293,  291,  289,  287,  285,
      283,  282,  279,  278,  277,  276,  274,  271,  270,  268,
      267,  266,  264,  261,  257,  255,  253,  252,  248,  247,
      246,  244,  242,  241,  238,  233,  230,  229,  227,  224,
      221,  219,  217,  212,  211,  210,  207,  203,  201,  199,
      197,  194,  192,  191,  184,  183,  181,  177,  173,  170,

      168,  167,  159,  151,  150,  148,  134,  132,  126,  125,
      121,  120,  114,  105,  104,   94,   26,    8,    5,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int rmap_flex_debug;
int rmap_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *rmaptext;
#line 1 "reader.l"
#line 2 "reader.l"
/*
 * static char *reader_l =
 *   "$Id: reader.l,v 1.2 2010/07/26 22:00:30 jastiv Exp $";
 */

/*
    CrossFire, A Multiplayer game for X-windows

    Copyright (C) 1994 Mark Wedel
    Copyright (C) 1992 Frank Tore Johansen

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

    The author can be reached via e-mail to mark@pyramid.com
*/



#include <global.h>
#include <loader.h>
#include <newserver.h>
#include <random_map.h>


#define YY_DECL int rmap_lex_read(RMParms *RP)

static char *rmap_yval(void);

static int rmap_lex_error;


#define IVAL	atoi(rmap_yval())
#define FVAL	atof(rmap_yval())


/* Don't have to link with -lfl with this */
/* need yy_push_state, yy_pop_state */
#line 804 "reader.c"

#define INITIAL 0
#define MESSAGE 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int rmaplex_destroy (void );

int rmapget_debug (void );

void rmapset_debug (int debug_flag  );

YY_EXTRA_TYPE rmapget_extra (void );

void rmapset_extra (YY_EXTRA_TYPE user_defined  );

FILE *rmapget_in (void );

void rmapset_in  (FILE * _in_str  );

FILE *rmapget_out (void );

void rmapset_out  (FILE * _out_str  );

yy_size_t rmapget_leng (void );

char *rmapget_text (void );

int rmapget_lineno (void );

void rmapset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int rmapwrap (void );
#else
extern int rmapwrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state (int _new_state );
    
    static void yy_pop_state (void );
    
    static int yy_top_state (void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( rmaptext, rmapleng, 1, rmapout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( rmapin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( rmapin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, rmapin))==0 && ferror(rmapin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(rmapin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int rmaplex (void);

#define YY_DECL int rmaplex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after rmaptext and rmapleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( rmapleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(rmaptext[rmapleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! rmapin )
			rmapin = stdin;

		if ( ! rmapout )
			rmapout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			rmapensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				rmap_create_buffer(rmapin,YY_BUF_SIZE );
		}

		rmap_load_buffer_state( );
		}

	{
#line 63 "reader.l"



/* Declare some local variables */

    rmap_lex_error=0;






#line 1049 "reader.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of rmaptext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 339 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 620 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 75 "reader.l"
strncpy(RP->wallstyle,rmap_yval(),RM_SIZE);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 76 "reader.l"
strncpy(RP->floorstyle,rmap_yval(),RM_SIZE);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 77 "reader.l"
strncpy(RP->monsterstyle,rmap_yval(),RM_SIZE);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 78 "reader.l"
strncpy(RP->treasurestyle,rmap_yval(),RM_SIZE);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 79 "reader.l"
strncpy(RP->layoutstyle,rmap_yval(),RM_SIZE);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 80 "reader.l"
strncpy(RP->doorstyle,rmap_yval(),RM_SIZE);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 81 "reader.l"
strncpy(RP->decorstyle,rmap_yval(),RM_SIZE);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 82 "reader.l"
RP->Xsize = IVAL;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 83 "reader.l"
RP->Ysize = IVAL;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 84 "reader.l"
RP->expand2x = IVAL;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 85 "reader.l"
RP->layoutoptions1 = IVAL;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 86 "reader.l"
RP->layoutoptions2 = IVAL;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 87 "reader.l"
RP->layoutoptions3 = IVAL;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 88 "reader.l"
RP->symmetry = IVAL;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 89 "reader.l"
RP->difficulty = IVAL;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 90 "reader.l"
RP->difficulty_increase = FVAL;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 91 "reader.l"
RP->decoroptions = IVAL;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 92 "reader.l"
strncpy(RP->exitstyle,rmap_yval(),RM_SIZE);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 93 "reader.l"
RP->dungeon_level = IVAL;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 94 "reader.l"
strncpy(RP->dungeon_name, rmap_yval(),RM_SIZE);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 95 "reader.l"
RP->dungeon_depth = IVAL;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 96 "reader.l"
strncpy(RP->final_map,rmap_yval(),RM_SIZE);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 97 "reader.l"
RP-> orientation = IVAL;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 98 "reader.l"
RP->origin_x = IVAL;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 99 "reader.l"
RP-> origin_y = IVAL;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 100 "reader.l"
strncpy(RP->origin_map,rmap_yval(),RM_SIZE);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 101 "reader.l"
RP->random_seed = IVAL;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 102 "reader.l"
RP->treasureoptions = IVAL;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 103 "reader.l"
strncpy(RP->addmusic,rmap_yval(),RM_SIZE);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 104 "reader.l"
strncpy(RP->exit_on_final_map,rmap_yval(),RM_SIZE);
	YY_BREAK
case 31:
/* rule 31 can match eol */
YY_RULE_SETUP
#line 106 "reader.l"
{/* ignore empty lines, newlines we don't do above */}
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 107 "reader.l"
{}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(MESSAGE):
#line 109 "reader.l"
{/* If we got an error, return the error.  Otherwise, return that we got EOF */
			    if (rmap_lex_error!=0) return rmap_lex_error; else return LL_EOF;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 111 "reader.l"
{ yyerror( "Unrecognized string"); rmap_lex_error= -1; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 112 "reader.l"
ECHO;
	YY_BREAK
#line 1285 "reader.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed rmapin at a new source and called
			 * rmaplex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = rmapin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( rmapwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * rmaptext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of rmaplex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					rmaprealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			rmaprestart(rmapin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) rmaprealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 339 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 339 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 338);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up rmaptext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					rmaprestart(rmapin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( rmapwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve rmaptext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void rmaprestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        rmapensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            rmap_create_buffer(rmapin,YY_BUF_SIZE );
	}

	rmap_init_buffer(YY_CURRENT_BUFFER,input_file );
	rmap_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void rmap_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		rmappop_buffer_state();
	 *		rmappush_buffer_state(new_buffer);
     */
	rmapensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	rmap_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (rmapwrap()) processing, but the only time this flag
	 * is looked at is after rmapwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void rmap_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	rmapin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE rmap_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) rmapalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in rmap_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) rmapalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in rmap_create_buffer()" );

	b->yy_is_our_buffer = 1;

	rmap_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with rmap_create_buffer()
 * 
 */
    void rmap_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		rmapfree((void *) b->yy_ch_buf  );

	rmapfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a rmaprestart() or at EOF.
 */
    static void rmap_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	rmap_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then rmap_init_buffer was _probably_
     * called from rmaprestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void rmap_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		rmap_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void rmappush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	rmapensure_buffer_stack();

	/* This block is copied from rmap_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from rmap_switch_to_buffer. */
	rmap_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void rmappop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	rmap_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		rmap_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void rmapensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; // After all that talk, this was set to 1 anyways...
		(yy_buffer_stack) = (struct yy_buffer_state**)rmapalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in rmapensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)rmaprealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in rmapensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE rmap_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) rmapalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in rmap_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	rmap_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to rmaplex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       rmap_scan_bytes() instead.
 */
YY_BUFFER_STATE rmap_scan_string (yyconst char * yystr )
{
    
	return rmap_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to rmaplex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE rmap_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) rmapalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in rmap_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = rmap_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in rmap_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) rmapalloc(new_size  );

		else
			(yy_start_stack) = (int *) rmaprealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up rmaptext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		rmaptext[rmapleng] = (yy_hold_char); \
		(yy_c_buf_p) = rmaptext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		rmapleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int rmapget_lineno  (void)
{
        
    return rmaplineno;
}

/** Get the input stream.
 * 
 */
FILE *rmapget_in  (void)
{
        return rmapin;
}

/** Get the output stream.
 * 
 */
FILE *rmapget_out  (void)
{
        return rmapout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t rmapget_leng  (void)
{
        return rmapleng;
}

/** Get the current token.
 * 
 */

char *rmapget_text  (void)
{
        return rmaptext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void rmapset_lineno (int  _line_number )
{
    
    rmaplineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see rmap_switch_to_buffer
 */
void rmapset_in (FILE *  _in_str )
{
        rmapin = _in_str ;
}

void rmapset_out (FILE *  _out_str )
{
        rmapout = _out_str ;
}

int rmapget_debug  (void)
{
        return rmap_flex_debug;
}

void rmapset_debug (int  _bdebug )
{
        rmap_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from rmaplex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    rmapin = stdin;
    rmapout = stdout;
#else
    rmapin = (FILE *) 0;
    rmapout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * rmaplex_init()
     */
    return 0;
}

/* rmaplex_destroy is for both reentrant and non-reentrant scanners. */
int rmaplex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		rmap_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		rmappop_buffer_state();
	}

	/* Destroy the stack itself. */
	rmapfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        rmapfree((yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * rmaplex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *rmapalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *rmaprealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void rmapfree (void * ptr )
{
			free( (char *) ptr );	/* see rmaprealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 112 "reader.l"



/*int yyerror(char *s)
{
  return -1;
}
*/

/* Our save file syntax is very simple, so we can use a very simple
 * processing mechanism here instead using something like bison
 * This skips over the space and returns the value, or "" if no value
 * is found.
 */
static char *rmap_yval()
{
    static char *em="";
    char *cp;

    cp=strchr(rmaptext,' ');
    if (cp) return cp+1;
    else return em;
}




int load_parameters(FILE *fp, int bufstate,RMParms *RP) {
    int retval;
    char inbuf[MAX_BUF];

    if (bufstate==LO_NEWFILE || bufstate==LO_NOREAD) {
        rmap_delete_buffer(YY_CURRENT_BUFFER);
        rmap_switch_to_buffer(rmap_create_buffer(fp,YY_BUF_SIZE));
        if (bufstate==LO_NOREAD) return LL_NORMAL;
    } 
    if (bufstate==LO_LINEMODE) {
        YY_BUFFER_STATE  yybufstate;
        while (fgets(inbuf, MAX_BUF-3, fp)) {
            yybufstate=rmap_scan_string(inbuf);
            retval=rmap_lex_read(RP);
            rmap_delete_buffer(yybufstate);
            if (retval==LL_NORMAL) return retval;
        }
        return LL_EOF;
    }

    retval=rmap_lex_read(RP);
/*    LOG(llevDebug," load completed, object=%s\n",op->name);*/
    return retval;
}


/* This takes a buffer, scans it for variables, and sets those variables
 * as appropriate in op.
 *
 * This function appears to be used in only 2 places - in wogedit to
 * override values and in c_wiz to mutate values.
 */
int set_random_map_variable(RMParms *rp,const char *buf) {
    YY_BUFFER_STATE  yybufstate;
    int retval;

    yybufstate=rmap_scan_string(buf);
    retval=rmap_lex_read(rp);
    rmap_delete_buffer(yybufstate);
    return retval;
}

